# Numpy practice session

In [1]:
#pip intall numpy
import numpy as np

#https://numpy.org/doc/stable/user/absolute_beginners.html

## creating an array using numpy

In [2]:
# 1-D array type
food = np.array(["Pakora", "Samosa", "Raita"])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [3]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [4]:
type(price)

numpy.ndarray

In [5]:
len(price)

3

In [6]:
price[2]

5

In [7]:
price[0:2]

array([5, 5])

In [8]:
food[1]

'Samosa'

In [9]:
price.mean() #to get array mean

5.0

In [11]:
# zeros method
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [12]:
# array of ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
# array of empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [14]:
# array of range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# specify the range
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [16]:
# specific interval in range
np.arange(2,20,2) # the last 2 defines the interval

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [19]:
# linear speace in an array, both lines of codes below are sam
np.linspace(5,25,3)
np.linspace(5,25,num=3)

array([ 5., 15., 25.])

In [21]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [23]:
# specify your data type
np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [24]:
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Array functions

In [25]:
a=np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [26]:
# sorting
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [28]:
b=np.array([10.5,14,200,34.5,0.5,12.8,0.3])
b

array([ 10.5,  14. , 200. ,  34.5,   0.5,  12.8,   0.3])

In [30]:
np.concatenate(((a,b)))

array([5.00e-01, 2.00e+00, 4.00e+00, 6.00e+00, 1.00e+01, 1.03e+01,
       1.20e+01, 1.50e+01, 1.00e+02, 3.20e+02, 1.05e+01, 1.40e+01,
       2.00e+02, 3.45e+01, 5.00e-01, 1.28e+01, 3.00e-01])

In [33]:
# concatenate 2 arrays and then sort
c = np.array([2,3,4,5,6])
d = np.array([1,3,5,2,4,1,43])
e = np.concatenate((c,d))
e

array([ 2,  3,  4,  5,  6,  1,  3,  5,  2,  4,  1, 43])

In [35]:
e.sort()
e

array([ 1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6, 43])

In [37]:
# 2-D arrays
a = np.array([[1,2,3,4,5],[5,4,3,2,1]])
a

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [40]:
b = np.array([[6,7,8,9,10],[8,9,10,11,12]])
b

array([[ 6,  7,  8,  9, 10],
       [ 8,  9, 10, 11, 12]])

In [41]:
c = np.concatenate((a,b)) # when concatenating two 2-D arrays both of them have same j and k i.e. row and cols.
c

array([[ 1,  2,  3,  4,  5],
       [ 5,  4,  3,  2,  1],
       [ 6,  7,  8,  9, 10],
       [ 8,  9, 10, 11, 12]])

In [42]:
np.concatenate((a,b), axis=0) #axis=0 is vertical axis

array([[ 1,  2,  3,  4,  5],
       [ 5,  4,  3,  2,  1],
       [ 6,  7,  8,  9, 10],
       [ 8,  9, 10, 11, 12]])

In [43]:
np.concatenate((a,b), axis=1) #axis=0 is horizontal axis

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 5,  4,  3,  2,  1,  8,  9, 10, 11, 12]])

In [45]:
# 3-D array
a = np.array([[[0,1,2,3],
             [4,5,6,7]],
             
             [[0,1,2,3],
             [4,5,6,7]],
             
             [[0,1,2,3],
             [4,5,6,7]]])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [50]:
# to find the number of dimensions
a.ndim

3

In [52]:
b = np.array([[0,1,2,3],
              [4,5,6,7],
              [1,3,5,7]])
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [1, 3, 5, 7]])

In [53]:
b.ndim

2

In [54]:
type(a)

numpy.ndarray

In [55]:
type(b)

numpy.ndarray

In [56]:
a.size #size of number of elements

24

In [57]:
b.size

12

In [58]:
a.shape # i,j, k means 3 metrices, 2 rows and 4 columns 

(3, 2, 4)

In [59]:
b.shape # i,j, k means 1 matrix, 3 rows and 4 columns, if NO i it means its a 2-D array 

(3, 4)

In [62]:
a = np.arange(6) #3*2
a

array([0, 1, 2, 3, 4, 5])

In [63]:
# reshape the array but to reshape the array should be able to be divided into givesn row and cols
a = a.reshape(3,2) # 3*2=6
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [68]:
np.reshape(a, newshape=(1,6), order="C") # check the documentation for 'C' like what else can come here?

array([[0, 1, 2, 3, 4, 5]])

In [69]:
# convert 1-D into 2-D
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
a.shape #its a single dimensional array with 9 as last element

(9,)

In [72]:
# convert 1-D to 2-D Row wise
b = a[np.newaxis, :] 
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [73]:
b.shape # now a is converted into 2 dimensional matrix with 1 row and 9 cols as last elements in each axis

(1, 9)

In [74]:
# Column wise convert 1-D to 2-D
c = a[ : , np.newaxis] 
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [75]:
c.shape # 2-D array with 9 rows and 1 col.

(9, 1)

In [76]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
# Indexing
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [78]:
a*6 # all elements in a are multiplied by 6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [79]:
a+6 # all elements in a are plus by 6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [80]:
a.sum() # sum of the array

45

In [81]:
a.mean() #mean of array

5.0