# NumPy

In [1]:
# import library
import numpy as np

In [2]:
a = np.array([5,5,5])
a
len(a)
type(a)

numpy.ndarray

In [3]:
b = np.zeros(2) 
b

array([0., 0.])

In [4]:
c = np.ones(3)
c

array([1., 1., 1.])

In [5]:
#create an empty array with 3 elements
d = np.empty(3)
d

array([1., 1., 1.])

In [6]:
#cwith range of elements
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [7]:
# with specific range of elements
a = np.arange(2,20)
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [8]:
# continue array with specific distance
a = np.arange(2,20,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
#linearly spaced arrays
a = np.linspace(0,10, num=5)#gives 5 numbers, all numbers in array will have linear/same distances among them
a

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [10]:
# specific data types in arrays
i = np.ones(5, dtype=np.int8) #google what in np.int8 or np.int64 
i

array([1, 1, 1, 1, 1], dtype=int8)

In [11]:
# specific data types exmple float
j = np.ones(5, dtype=np.float64) ##google what in np.float8 or np.float64 
j

array([1., 1., 1., 1., 1.])

### Making 2D arrays

In [12]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
b = np.ones((5,6))
b

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [14]:
c = np.empty((3,4))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Making 3D arrays

In [15]:
#making and reshaping a 3D array
a = np.arange(24).reshape(2,3,4) #here, remember i,j and k in alphabet order where i=no of arrays, 
                                    # j=no of rows, k=no of cols.
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])